version: "3.9"

services:
  webhook-api:
    build:
      dockerfile: Dockerfile
    container_name: webhook-api
    restart: always
    ports:
      - "8081:8080"
    networks:
      - mensageria

networks:
  mensageria:
    external: true
